name: Windows

on:
  workflow_call:
    inputs:
      package:
        description: "Build full packages (true) or just test compilation (false)"
        required: true
        type: boolean
      with_webview:
        description: "Build with wxWebView support"
        required: false
        type: string
        default: "false"

jobs:
  build:
    name: amd64
    env:
      DOCKER_BUILD_SUMMARY: false
      DOCKER_BUILD_RECORD_UPLOAD: false  
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Compile check
        if: ${{ !inputs.package }}
        uses: docker/build-push-action@v7
        with:
          context: .
          target: compile-win64
          push: false
          build-args: |
            WITH_WEBVIEW=${{ inputs.with_webview }}
          cache-from: type=gha,scope=windows-amd64-webview-${{ inputs.with_webview }}
          cache-to: type=gha,mode=max,scope=windows-amd64-webview-${{ inputs.with_webview }}

      - name: Build & package
        if: ${{ inputs.package }}
        uses: docker/build-push-action@v7
        with:
          context: .
          target: export-win64
          push: false
          outputs: type=local,dest=dist
          build-args: |
            WITH_WEBVIEW=${{ inputs.with_webview }}
          cache-from: type=gha,scope=windows-amd64-webview-${{ inputs.with_webview }}
          cache-to: type=gha,mode=max,scope=windows-amd64-webview-${{ inputs.with_webview }}

      - name: List produced packages
        if: ${{ inputs.package }}
        run: du -sh dist/**

      - name: Upload artifacts
        if: ${{ inputs.package }}
        uses: actions/upload-artifact@v5
        with:
          name: windows-amd64-packages
          path: dist/**
          if-no-files-found: error
